version: '3.3'

# Define services
services:
  # App backend service
  ergastapi:
    # Configuration for building the docker image for the backend service
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports:
      - "9000:8890" # Forward the exposed port 8890 on the container to port 9000 on the host machine
    restart: always